function content()

cstr={'Figures 1, S2: lh_two_site_comp.m',...
    'Figure2: soil_moisture_evaluation_vsobs.m',...
    'Figure S3, S5: site_HD_eval_soimoist.m',...
    'Figure S4: lh_tapajos.m',...
    'Figure 3: sierr_tstep_solver.m',...
    'Figure 4: hdr_solverdiff.m',...
    'Figure 5 and 6: vegetation_removal_annual.m',...
    'Figure 7, 9 and S6: fluxnet_clm_ET_correlation.m',...
    'Figure 8: global_statistics_model_vs_fluxnet_mte.m',...
    'Figure 10, 11, 12 and S8: tws_vs_grace_comparison.m',...
    'Figure 13: lat_bin_annual_ET_kx.m',...
    'Figure S7: tws_vs_clm_bad_site.m',...
    'Figure S9 and S10: lat_bin_annual_ET_fpedotransfer.m',...
    'Figure 14, S1: site_level_zwt_comp.m',...
    'global ET statistics: global_average_difference.m'};


disp(cstr);
end